services:
  # --- PostgreSQL ---
  postgres:
    image: postgres:16-alpine
    container_name: photo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photo_analysis
    ports:
      - "5435:5432"  # Внешний порт 5435 -> Внутренний 5432
    volumes:
      - pg_data:/var/lib/postgresql/data # Постоянное хранилище данных

  # --- MinIO ---
  minio:
    image: minio/minio:latest
    container_name: photo-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9100:9000"  # S3 API
      - "9101:9001"  # Web Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  kafka:
    image: apache/kafka:latest
    container_name: photo-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_PLAINTEXT_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_PLAINTEXT_PLAIN_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin"
        password="admin-secret"
        user_admin="admin-secret"
        user_photo-api="photo-api-secret";

  api:
    build: .
    container_name: photo-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres                # имя сервиса
      DB_PORT: 5432                     # внутренний порт postgres
      DB_NAME: photo_analysis
      MINIO_ENDPOINT: minio:9000       # имя сервиса + S3 API порт
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_BUCKET_NAME: photo-bucket
      MINIO_PUBLIC_URL: localhost:9100
      LOG_LEVEL: INFO
      DB_ECHO: "false"

# Объявляем тома (volumes), чтобы данные не терялись
volumes:
  pg_data:
  minio_data: