apiVersion: v1
kind: Secret
metadata:
  name: umnaya-secret
  namespace: umnaya
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin123"
  VK_SECRET_KEY: "YK832M5Ut8tpgr8ITiQA"