"""add_photo_analysis_fields_blur_score_dominant_color_tags_model_version

Revision ID: 472ec77dc88b
Revises: 97952d5ba82e
Create Date: 2026-07-21 12:49:04.212867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472ec77dc88b'
down_revision: Union[str, Sequence[str], None] = '97952d5ba82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_analysis', sa.Column('dominant_color', sa.String(length=7), nullable=True))
    op.add_column('photo_analysis', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('photo_analysis', sa.Column('model_version', sa.String(length=20), nullable=True))
    op.alter_column('photo_analysis', 'blur_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo_analysis', 'blur_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('photo_analysis', 'model_version')
    op.drop_column('photo_analysis', 'tags')
    op.drop_column('photo_analysis', 'dominant_color')
    # ### end Alembic commands ###
