"""empty message

Revision ID: 97952d5ba82e
Revises: 
Create Date: 2026-07-20 14:20:38.815450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97952d5ba82e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('data_token', sa.String(length=255), nullable=False),
    sa.Column('auth_token', sa.String(length=255), nullable=False),
    sa.Column('vk_owner_user_id', sa.String(length=50), nullable=False),
    sa.Column('created_at_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('data_token'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_string', sa.String(length=36), nullable=False),
    sa.Column('owner_data_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_identity_group', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('standart_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_data_token'], ['tokens.data_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id_string'), 'groups', ['id_string'], unique=True)
    op.create_index(op.f('ix_groups_owner_data_token'), 'groups', ['owner_data_token'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_string', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('preview_key', sa.String(length=500), nullable=True),
    sa.Column('load_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('photo_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'pending', 'processing', 'done', 'failed', name='photostatuses'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.Integer(), nullable=True),
    sa.Column('last_error_message', sa.String(length=1000), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('owner_data_token', sa.String(length=255), nullable=True),
    sa.Column('duplicate_group_id', sa.Integer(), nullable=True),
    sa.Column('identity_photo_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['identity_photo_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_data_token'], ['tokens.data_token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_duplicate_group_id'), 'photos', ['duplicate_group_id'], unique=False)
    op.create_index(op.f('ix_photos_id_string'), 'photos', ['id_string'], unique=True)
    op.create_index(op.f('ix_photos_identity_photo_group_id'), 'photos', ['identity_photo_group_id'], unique=False)
    op.create_index(op.f('ix_photos_owner_data_token'), 'photos', ['owner_data_token'], unique=False)
    op.create_table('photo_analysis',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('faces_count', sa.Integer(), nullable=True),
    sa.Column('eyes_closed_count', sa.Integer(), nullable=True),
    sa.Column('is_blurred', sa.Boolean(), nullable=True),
    sa.Column('blur_score', sa.Integer(), nullable=True),
    sa.Column('quality_metric', sa.Integer(), nullable=True),
    sa.Column('light_level', sa.Integer(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index(op.f('ix_photo_analysis_perceptual_hash'), 'photo_analysis', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_photo_analysis_sha256_hash'), 'photo_analysis', ['sha256_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_analysis_sha256_hash'), table_name='photo_analysis')
    op.drop_index(op.f('ix_photo_analysis_perceptual_hash'), table_name='photo_analysis')
    op.drop_table('photo_analysis')
    op.drop_index(op.f('ix_photos_owner_data_token'), table_name='photos')
    op.drop_index(op.f('ix_photos_identity_photo_group_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_id_string'), table_name='photos')
    op.drop_index(op.f('ix_photos_duplicate_group_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_groups_owner_data_token'), table_name='groups')
    op.drop_index(op.f('ix_groups_id_string'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('tokens')
    # ### end Alembic commands ###
